language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - mkdir cmake
  - cd cmake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.sh
  - sh cmake-3.2.2-Linux-x86_64.sh --exclude-subdir --skip-license
  - alias cmake=`pwd`/bin/cmake
  - cd ..

  - sudo apt-get install -y libgtest-dev
  - mkdir gtest_build
  - cd gtest_build
  - cmake /usr/src/gtest
  - make
  - sudo cp *.a /usr/lib
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./lzc_test
