language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libgtest-dev
  - sudo apt-get install -y cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./lzc_test
